2D AMRCLAW: amr2.f90 File Reference
amr2.f90 File Reference
Functions/Subroutines
program amr2
Function/Subroutine Documentation
amr2()
program amr2 ()
Definition at line 56 of file amr2.f90.
References amr_module::auxtype, amr_module::avenumgrids, amr_module::cfl, amr_module::cflmax, amr_module::cflv1, amr_module::check_a, amr_module::checkpt_interval, amr_module::checkpt_style, cleanup(), conck(), amr_module::dbugunit, amr_module::dimensional_split, domain(), amr_module::dprint, amr_module::edebug, amr_module::eprint, amr_module::evol, amr_module::flag_gradient, amr_module::flag_richardson, amr_module::gprint, amr_module::hxposs, amr_module::hyposs, amr_module::ibuff, amr_module::iinfinity, amr_module::intratx, amr_module::intraty, amr_module::inunit, amr_module::iorder, amr_module::iout, amr_module::iregridcount, amr_module::kcheck, amr_module::kratio, amr_module::lendim, amr_module::lenmax, amr_module::lentot, amr_module::lfine, amr_module::matlabu, amr_module::matunit, amr_module::max1d, amr_module::maxlv, amr_module::maxvar, amr_module::mcapa, amr_module::method, amr_module::mstart, amr_module::mthbc, amr_module::mthlim, amr_module::mwaves, amr_module::mxnest, amr_module::nchkpt, amr_module::nghost, amr_module::nout, amr_module::nprint, amr_module::nstop, gauges_module::num_gauges, amr_module::numgrids, opendatafile(), amr_module::output_aux_components, amr_module::output_aux_onlyonce, amr_module::output_format, amr_module::output_q_components, amr_module::output_style, outtre(), amr_module::outunit, amr_module::parmunit, amr_module::possk, amr_module::pprint, amr_module::printout, restrt(), amr_module::rinfinity, amr_module::rprint, amr_module::rstfile, amr_module::rvol, amr_module::rvoll, gauges_module::set_gauges(), regions_module::set_regions(), setgrd(), setprob(), amr_module::spheredom, amr_module::sprint, stst1(), amr_module::t0, amr_module::tchk, amr_module::tfinal, tick(), amr_module::timebound, amr_module::timeboundcpu, amr_module::timebufnst, amr_module::timeflagger, amr_module::timeregridding, amr_module::timeregriddingcpu, amr_module::timestepgrid, amr_module::timestepgridcpu, amr_module::timetick, amr_module::timetickcpu, amr_module::timeupdating, amr_module::timevalout, amr_module::timevaloutcpu, amr_module::tol, amr_module::tolsp, amr_module::tout, amr_module::tprint, amr_module::tstart_thisrun, amr_module::tvoll, amr_module::tvollcpu, amr_module::uprint, amr_module::use_fwaves, valout(), amr_module::verbosity_regrid, amr_module::xlower, amr_module::xperdom, amr_module::xupper, amr_module::ylower, amr_module::yperdom, and amr_module::yupper.