2D AMRCLAW: flux2_dimSplit.f File Reference
flux2_dimSplit.f File Reference
Functions/Subroutines
subroutine flux2_dimsplit (ixy, maxm, meqn, maux, mbc, mx, q1d, dtdx1d, aux2, faddm, faddp, cfl1d, wave, s, cqxx, rpn2)
Function/Subroutine Documentation
flux2_dimsplit()
subroutine flux2_dimsplit (ixy, maxm, meqn, maux, mbc, mx, dimension(meqn,1-mbc:maxm+mbc) q1d, dimension(1-mbc:maxm+mbc) dtdx1d, dimension(maux,1-mbc:maxm+mbc) aux2, dimension(meqn,1-mbc:maxm+mbc) faddm, dimension(meqn,1-mbc:maxm+mbc) faddp, cfl1d, dimension(meqn, mwaves, 1-mbc:maxm+mbc) wave, dimension(mwaves, 1-mbc:maxm+mbc) s, dimension(meqn,1-mbc:maxm+mbc) cqxx, external rpn2)
Definition at line 8 of file flux2_dimSplit.f.
References limiter(), amr_module::method, amr_module::mthlim, amr_module::mwaves, rpn2(), and amr_module::use_fwaves.
Referenced by step2x(), and step2y().
 c     =====================================================
 c
 c     # clawpack routine ...  modified for AMRCLAW
 c
 c     # Compute the modification to fluxes f and g that are generated by
 c     # all interfaces along a 1D slice of the 2D grid.
 c     #    ixy = 1  if it is a slice in x
 c     #          2  if it is a slice in y
 c     # This value is passed into the Riemann solvers. The flux modifications
 c     # go into the arrays fadd and gadd.  The notation is written assuming
 c     # we are solving along a 1D slice in the x-direction.
 c
 c     # fadd(*,i,.) modifies F to the left of cell i
 c     # gadd(*,i,.,1) modifies G below cell i
 c     # gadd(*,i,.,2) modifies G above cell i
 c
 c     # The method used is specified by method(2:3):
 c
 c         method(2) = 1 if only first order increment waves are to be used.
 c                   = 2 if second order correction terms are to be added, with
 c                       a flux limiter as specified by mthlim.
 c
 c         method(3) = 0 if no transverse propagation is to be applied.
 c                       Increment and perhaps correction waves are propagated
 c                       normal to the interface.
 c                   = 1 if transverse propagation of increment waves
 c                       (but not correction waves, if any) is to be applied.
 c                   = 2 if transverse propagation of correction waves is also
 c                       to be included.
 c
 c     Note that if mcapa>0 then the capa array comes into the second
 c     order correction terms, and is already included in dtdx1d:
 c     If ixy = 1 then
 c        dtdx1d(i) = dt/dx                      if mcapa= 0
 c                  = dt/(dx*aux(mcapa,i,jcom))  if mcapa = 1
 c     If ixy = 2 then
 c        dtdx1d(j) = dt/dy                      if mcapa = 0
 c                  = dt/(dy*aux(mcapa,icom,j))  if mcapa = 1
 c
 c     Notation:
 c        The jump in q (q1d(i,:)-q1d(i-1,:))  is split by rpn2 into
 c            amdq =  the left-going flux difference  A^- Delta q
 c            apdq = the right-going flux difference  A^+ Delta q
 c      In dimensionally split version no need for extra arrays amdq,apdq
 c      Use faddm and faddp instead. BUT REMEMBER to negate apdq
 c      since it was previously SUBTRACTED from fadpp.
 c
 c
       use amr_module
       implicit double precision (a-h,o-z)
       external rpn2
       dimension    q1d(meqn,1-mbc:maxm+mbc)
       dimension   cqxx(meqn,1-mbc:maxm+mbc)
       dimension   faddm(meqn,1-mbc:maxm+mbc)
       dimension   faddp(meqn,1-mbc:maxm+mbc)
       dimension dtdx1d(1-mbc:maxm+mbc)
       dimension aux2(maux,1-mbc:maxm+mbc)
 c
       dimension     s(mwaves, 1-mbc:maxm+mbc)
       dimension  wave(meqn, mwaves, 1-mbc:maxm+mbc)
 c
       logical limit
 c
       limit = .false.
       do 5 mw=1,mwaves
          if (mthlim(mw) .gt. 0) limit = .true.
    5     continue
 c
 c     # initialize flux increments:
 c     -----------------------------
 c
        do 10 i = 1-mbc, mx+mbc
          do 20 m=1,meqn
             faddm(m,i) = 0.d0
             faddp(m,i) = 0.d0
    20    continue
    10  continue
 c
 c
 c     # solve Riemann problem at each interface and compute Godunov updates
 c     ---------------------------------------------------------------------
 c
       call rpn2(ixy,maxm,meqn,mwaves,maux,mbc,mx,q1d,q1d,
      &          aux2,aux2,wave,s,faddm,faddp)
 c
       faddp = -faddp  !! NEGATED, replaces faddp(m,i) = faddp(m,i) - apdq(m,i) in original flux2.
 c
 c     # dont delete this code yet, in case there is an issue with loop indices
 !     # Set fadd for the donor-cell upwind method (Godunov)
 !--      do 40 i=1,mx+1
 !--         do 40 m=1,meqn
 !--            faddp(m,i) = faddp(m,i) - apdq(m,i)
 !--            faddm(m,i) = faddm(m,i) + amdq(m,i)
 !--   40       continue
 c
 c     # compute maximum wave speed for checking Courant number:
       cfl1d = 0.d0
       do 50 mw=1,mwaves
          do 50 i=1,mx+1
 c          # if s>0 use dtdx1d(i) to compute CFL,
 c          # if s<0 use dtdx1d(i-1) to compute CFL:
             cfl1d = dmax1(cfl1d, dtdx1d(i)*s(mw,i),
      &                          -dtdx1d(i-1)*s(mw,i))
    50       continue
 c
       if (method(2).eq.1) go to 130
 c
 c     # modify F fluxes for second order q_{xx} correction terms:
 c     -----------------------------------------------------------
 c
 c     # apply limiter to waves:
       if (limit) call limiter(maxm,meqn,mwaves,mbc,mx,wave,s,mthlim)
 c
       do 120 i = 1, mx+1
 c
 c        # For correction terms below, need average of dtdx in cell
 c        # i-1 and i.  Compute these and overwrite dtdx1d:
 c
 c        # modified in Version 4.3 to use average only in cqxx, not transverse
          dtdxave = 0.5d0 * (dtdx1d(i-1) + dtdx1d(i))
 c
 c        # second order corrections:
          do 120 m=1,meqn
             cqxx(m,i) = 0.d0
             do 119 mw=1,mwaves
 c
                if (use_fwaves) then
                    abs_sign = dsign(1.d0,s(mw,i))
                  else
                    abs_sign = dabs(s(mw,i))
                  endif
                cqxx(m,i) = cqxx(m,i) + abs_sign
      &             * (1.d0 - dabs(s(mw,i))*dtdxave) * wave(m,mw,i)
 c
   119          continue
             faddm(m,i) = faddm(m,i) + 0.5d0 * cqxx(m,i)
             faddp(m,i) = faddp(m,i) + 0.5d0 * cqxx(m,i)
   120       continue
 c
 c
   130  continue
 c
       return