2D AMRCLAW: amr_module Module Reference
amr_module Module Reference
The module contains the definition of a "node descriptor" as well as other global variables used during the whole run.
Variables
integer, parameter rsize = 5
integer, parameter nsize = 19
integer, parameter levelptr = 1
node number (index) of next grid on the same level
integer, parameter tempptr = 2
temporary pointer
integer, parameter errptr = 3
integer, parameter nestlevel = 4
AMR level of the grid.
integer, parameter cfluxptr = 5
Pointer to an 5 by maxsp array, which has boundary information for this grid.
integer, parameter ffluxptr = 6
pointer to the address of memory storing fluxes in a layer around the grid, to be used in conservation fixup near coarse-fine grid intersections.
integer, parameter store1 = 7
pointer to the address of memory storing the first copy of solution data on this grid, usually for storing new solution
integer, parameter store2 = 8
pointer to the address of memory storing the second copy of solution data on this grid, usually for storing old solution
integer, parameter ndilo = 9
global i index of left border of this grid
integer, parameter ndihi = 10
global i index of right border of this grid
integer, parameter ndjlo = 11
global j index of lower border of this grid
integer, parameter ndjhi = 12
global j index of upper border of this grid
integer, parameter storeaux = 13
pointer to the address of memory storing auxiliary data on this grid
integer, parameter storeflags = 14
pointer to the address of memory storing flags for refinement on this grid
integer, parameter numflags = 15
number of flagged cells on this grid
integer, parameter domflags_base = 16
domain flags, indexed within base level (lbase) index space
integer, parameter domflags2 = 17
domain flags, indexed within level-of-this-grid level index space
integer, parameter bndlistst = 18
pointer (actually it's an index in the bndList array) to the first node of a linked list, which stores all grids (on the same level) that border this grid
integer, parameter bndlistnum = 19
number of grids (on the same level) that border this grid
integer, parameter cornxlo = 1
x-coordinate of the left border of this grid
integer, parameter cornylo = 2
y-coordinate of the lower border of this grid
integer, parameter cornxhi = 3
x-coordinate of the right border of this grid
integer, parameter cornyhi = 4
y-coordinate of the upper border of this grid
integer, parameter timemult = 5
current simulation time on this grid
integer, parameter nextfree = 2
integer, parameter null = 0
integer, parameter nil = 0
integer, parameter gridnbor = 1
real(kind=8), parameter goodpt = 0.0
real(kind=8), parameter badpt = 2.0
real(kind=8), parameter badpro = 3.0
real(kind=8), parameter needs_to_be_set = 10.e33
real(kind=8), parameter rinfinity = 10.e32
integer, parameter iinfinity = 999999999
integer, parameter horizontal = 1
integer, parameter vertical = 2
integer, parameter maxgr = 15000
integer, parameter maxlv = 10
integer, parameter maxcl = 5000
maximum number of clusters (grids) on each grid level
integer, parameter max1d = 60
integer, parameter maxvar = 10
integer, parameter maxaux = 20
integer, parameter maxwave = 10
integer, dimension(maxgr) listofgrids
integer, dimension(0:maxlv+1) liststart
integer, parameter bndlistsize = 8*maxgr
integer, dimension(bndlistsize, 2) bndlist
real(kind=8), dimension(maxlv) hxposs
real(kind=8), dimension(maxlv) hyposs
real(kind=8), dimension(maxlv) possk
real(kind=8), dimension(rsize, maxgr) rnode
real(kind=8) tol
real(kind=8) tolsp
integer ibuff
integer mstart
integer ndfree
integer ndfree_bnd
integer lfine
integer, dimension(nsize, maxgr) node
integer, dimension(maxlv) icheck
integer, dimension(maxlv) lstart
integer, dimension(maxlv) newstl
integer, dimension(maxlv) listsp
integer, dimension(maxlv) intratx
integer, dimension(maxlv) intraty
integer, dimension(maxlv) kratio
integer, dimension(maxlv) iregsz
integer, dimension(maxlv) jregsz
integer, dimension(maxlv) iregst
integer, dimension(maxlv) jregst
integer, dimension(maxlv) iregend
integer, dimension(maxlv) jregend
integer, dimension(maxlv) numgrids
integer, dimension(maxlv) numcells
integer iorder
integer mxnest
integer kcheck
real(kind=8), dimension(:), allocatable alloc
integer memsize
integer, parameter lfdim =5000
integer, dimension(lfdim, 2) lfree
integer lenf
logical xperdom
logical yperdom
logical spheredom
real(kind=8) xupper
real(kind=8) yupper
real(kind=8) xlower
real(kind=8) ylower
integer nghost
integer, dimension(4) mthbc
real(kind=8), dimension(maxlv) rvoll
real(kind=8) evol
real(kind=8) rvol
real(kind=8), dimension(maxlv) avenumgrids
integer, dimension(maxlv) iregridcount
integer, dimension(maxlv) tvoll
integer timeregridding
integer timeupdating
integer timevalout
integer timeflglvl
integer timegrdfit2
integer timegrdfit3
integer timegrdfitall
integer timebound
integer timestepgrid
integer timeflagger
integer timebufnst
integer timetick
real(kind=8), dimension(maxlv) tvollcpu
real(kind=8) timetickcpu
real(kind=8) timeboundcpu
real(kind=8) timestepgridcpu
real(kind=8) timeregriddingcpu
real(kind=8) timevaloutcpu
integer lentot
integer lenmax
integer lendim
character(len=10), dimension(:), allocatable auxtype
integer, dimension(7) method
integer mwaves
integer mcapa
integer dimensional_split
integer, dimension(:), allocatable mthlim
real(kind=8) cfl
real(kind=8) cflmax
real(kind=8) cflv1
real(kind=8) cfl_level
logical use_fwaves
logical flag_richardson
logical flag_gradient
integer verbosity_regrid
logical printout
logical matlabout
logical ncarout
real(kind=8) tmass0
integer output_style
integer nstop
integer nout
integer iout
real(kind=8), dimension(:), allocatable tout
real(kind=8) t0
real(kind=8) tfinal
real(kind=8) tstart_thisrun
integer nq_components
integer naux_components
integer output_format
integer, dimension(:), allocatable output_q_components
integer, dimension(:), allocatable output_aux_components
logical output_aux_onlyonce
integer checkpt_style
integer nchkpt
integer checkpt_interval
real(kind=8), dimension(:), allocatable tchk
integer matlabu
integer, parameter parmunit = 12
integer, parameter chkunit = 10
integer, parameter inunit = 5
integer, parameter outunit = 66
integer, parameter pltunit1 = 3
integer, parameter rstunit = 9
integer, parameter dbugunit = 11
integer, parameter matunit = 70
logical dprint
logical eprint
logical edebug
logical gprint
logical nprint
logical pprint
logical rprint
logical sprint
logical tprint
logical uprint
character(len=200) rstfile
logical check_a
Detailed Description
The module contains the definition of a "node descriptor" as well as other global variables used during the whole run.
The "node descriptor" is a tree data structure we use to keep track of all AMR grids. Each grid in the grid hierarchy corresponds to a node in the tree. When a fine grid is nested in a coarse grid, its corresponding node in the tree is an offspring of the parent node corresponding to the coarse grid.
Tree data structure for grid management
Each node has a fixed number of items of information describing the grid, stored and accessable as node(property number, node number) (which returns a integer type as either data itself or a pointer to a memory location) and rnode(property number, node number) (which returns a real type). E.g. node(nestlevel, 5) stores AMR level of grid 5. rnode(cornxlo, 3) stores x-coordinate of left border of grid 3.
See explanation to each data members in this module for details of all properties of a node.
Variable Documentation
alloc
real(kind=8), dimension(:), allocatable amr_module::alloc
Definition at line 218 of file amr_module.f90.
Referenced by advanc(), basecheck(), bufnst2(), check(), colate2(), conck(), domain(), domgrid(), errest(), filval(), flagger(), flglvl2(), fluxsv(), gfixup(), ginit(), grdfit(), icall(), init_alloc(), intcopy(), intfil(), outmsh(), par_advanc(), prefilrecur(), prepbigstep(), prepc(), prepf(), resize_storage(), restrt(), restrt_alloc(), saveqc(), setdomflags(), spest2(), upbnd(), update(), and valout().
     real(kind=8), allocatable, dimension(:) :: alloc    ! new way, use allocatable, not pointer
auxtype
character(len=10), dimension(:), allocatable amr_module::auxtype
Definition at line 252 of file amr_module.f90.
Referenced by amr2(), prepbigstep(), and qad().
     character(len=10), allocatable :: auxtype(:)
avenumgrids
real(kind=8), dimension(maxlv) amr_module::avenumgrids
Definition at line 237 of file amr_module.f90.
Referenced by amr2(), check(), domain(), regrid(), restrt(), setgrd(), and stst1().
badpro
real(kind=8), parameter amr_module::badpro = 3.0
Definition at line 166 of file amr_module.f90.
Referenced by projec2().
     real(kind=8), parameter :: badpro = 3.0
badpt
real(kind=8), parameter amr_module::badpt = 2.0
Definition at line 165 of file amr_module.f90.
Referenced by addflags(), bufnst2(), errf1(), flagger(), and spest2().
     real(kind=8), parameter :: badpt  = 2.0
bndlist
integer, dimension(bndlistsize,2) amr_module::bndlist
Definition at line 191 of file amr_module.f90.
Referenced by freebndrylist(), initbndrylist(), intfil(), makebndrylist(), nodget_bnd(), and putnod_bnd().
     integer :: bndlist(bndlistsize,2)  ! guess size, average # nbors 4? manage as linked list
bndlistnum
integer, parameter amr_module::bndlistnum = 19
number of grids (on the same level) that border this grid
Definition at line 139 of file amr_module.f90.
Referenced by freebndrylist(), intfil(), makebndrylist(), and nodget_bnd().
     integer, parameter :: bndlistnum = 19
bndlistsize
integer, parameter amr_module::bndlistsize = 8*maxgr
Definition at line 190 of file amr_module.f90.
Referenced by initbndrylist(), and nodget_bnd().
     integer,parameter :: bndlistsize = 8*maxgr
bndlistst
integer, parameter amr_module::bndlistst = 18
pointer (actually it's an index in the bndList array) to the first node of a linked list, which stores all grids (on the same level) that border this grid
Definition at line 136 of file amr_module.f90.
Referenced by freebndrylist(), intfil(), and makebndrylist().
     integer, parameter :: bndlistst  = 18
cfl
real(kind=8) amr_module::cfl
Definition at line 255 of file amr_module.f90.
Referenced by amr2(), domain(), stepgrid(), and stepgrid_dimsplit().
     real(kind=8) cfl,cflmax,cflv1,cfl_level
cfl_level
real(kind=8) amr_module::cfl_level
Definition at line 255 of file amr_module.f90.
Referenced by advanc(), stepgrid(), stepgrid_dimsplit(), and tick().
cflmax
real(kind=8) amr_module::cflmax
Definition at line 255 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), and restrt().
cfluxptr
integer, parameter amr_module::cfluxptr = 5
Pointer to an 5 by maxsp array, which has boundary information for this grid.
About the Array
The array is generally referred to as listbc. It stores information about interface between grid mptr and all grids one level finer if they intersect. These interfaces consist of multiple cell edges (or segments, whose length = cell size on grid mptr). Each column in listbc has five entries and stores information associated with one segment. If a global index for all these segments is denoted by ispot, the five entries for the segment can be explained as below:
listbc(1,ispot) stores LOCAL (RALATIVE to left boundary of grid mptr) i index of the cell on grid mptr that border this segment.
listbc(2,ispot) stores LOCAL (RALATIVE to left boundary of grid mptr) j index of the cell on grid mptr that border this segment.
listbc(3,ispot) stores side number, which indicates which side of this segment is a cell of grid mptr (coarse cell). If this segment is the left edge of a cell on grid mptr, this number is 1. The number increases (2, 3, 4) as it goes around a coarse cell clockwise (top edge, right edge, bottom edge).
listbc(4,ispot) stores grid number of the finer grid that borders this segment
listbc(5,ispot) stores the position of this segment with respect to the perimeter of this finer grid (grid listbc(4,ispot)). The fine grid will save all its fluxes all around its perimeter. This entry tells where the coarse grid should take them from. Note that number of fluxes saved here is equal to number of such segments (length = coarse cell size) needed to make up the perimeter.
Definition at line 80 of file amr_module.f90.
Referenced by outmsh(), par_advanc(), prepc(), putsp(), restrt(), and update().
     integer, parameter :: cfluxptr  = 5
cflv1
real(kind=8) amr_module::cflv1
Definition at line 255 of file amr_module.f90.
Referenced by amr2(), stepgrid(), and stepgrid_dimsplit().
check_a
logical amr_module::check_a
Definition at line 312 of file amr_module.f90.
Referenced by amr2(), check(), and restrt().
     logical :: check_a
checkpt_interval
integer amr_module::checkpt_interval
Definition at line 280 of file amr_module.f90.
Referenced by amr2(), and tick().
checkpt_style
integer amr_module::checkpt_style
Definition at line 280 of file amr_module.f90.
Referenced by amr2(), check(), and tick().
     integer :: checkpt_style, nchkpt, checkpt_interval
chkunit
integer, parameter amr_module::chkunit = 10
Definition at line 288 of file amr_module.f90.
Referenced by check().
     integer, parameter :: chkunit = 10
cornxhi
integer, parameter amr_module::cornxhi = 3
x-coordinate of the right border of this grid
Definition at line 147 of file amr_module.f90.
Referenced by birect(), bound(), domain(), gfixup(), grdfit(), nestck2(), outmsh(), saveqc(), and gauges_module::setbestsrc().
     integer, parameter :: cornxhi  = 3
cornxlo
integer, parameter amr_module::cornxlo = 1
x-coordinate of the left border of this grid
Definition at line 143 of file amr_module.f90.
Referenced by birect(), bound(), bufnst2(), domain(), errf1(), flagger(), gfixup(), ginit(), grdfit(), nestck2(), outmsh(), outval(), par_advanc(), prepbigstep(), prepregstep(), saveqc(), gauges_module::setbestsrc(), spest2(), and valout().
     integer, parameter :: cornxlo  = 1
cornyhi
integer, parameter amr_module::cornyhi = 4
y-coordinate of the upper border of this grid
Definition at line 149 of file amr_module.f90.
Referenced by birect(), bound(), domain(), gfixup(), grdfit(), nestck2(), outmsh(), saveqc(), and gauges_module::setbestsrc().
     integer, parameter :: cornyhi  = 4
cornylo
integer, parameter amr_module::cornylo = 2
y-coordinate of the lower border of this grid
Definition at line 145 of file amr_module.f90.
Referenced by birect(), bound(), bufnst2(), domain(), errf1(), flagger(), gfixup(), ginit(), grdfit(), nestck2(), outmsh(), outval(), par_advanc(), prepbigstep(), prepregstep(), saveqc(), gauges_module::setbestsrc(), spest2(), and valout().
     integer, parameter :: cornylo  = 2
dbugunit
integer, parameter amr_module::dbugunit = 11
Definition at line 293 of file amr_module.f90.
Referenced by amr2(), check(), fluxad(), fluxsv(), qad(), stepgrid(), and stepgrid_dimsplit().
     integer, parameter :: dbugunit = 11
dimensional_split
integer amr_module::dimensional_split
Definition at line 253 of file amr_module.f90.
Referenced by amr2(), and par_advanc().
domflags2
integer, parameter amr_module::domflags2 = 17
domain flags, indexed within level-of-this-grid level index space
Definition at line 132 of file amr_module.f90.
Referenced by bufnst2(), colate2(), domgrid(), freeflags(), and setdomflags().
     integer, parameter :: domflags2  = 17
domflags_base
integer, parameter amr_module::domflags_base = 16
domain flags, indexed within base level (lbase) index space
Definition at line 129 of file amr_module.f90.
Referenced by bufnst2(), colate2(), domgrid(), and freeflags().
     integer, parameter :: domflags_base  = 16
dprint
logical amr_module::dprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), domcopy(), domprep(), domshrink(), domup(), griddomshrink(), and griddomup().
     logical &
                 dprint,     & !  domain flags output
                 eprint,     & !  error estimation output
                 edebug,     & !  even more error estimation output
                 gprint,     & !  verbose grid generation (clustering,colating...)
                 nprint,     & !  nestck reporting
                 pprint,     & !  projec tagged pts.
                 rprint,     & !  regridding -  summary of new grids
                 sprint,     & !  space (memory) output
                 tprint,     & !  tick (time stepping) reporting
                 uprint        !  updating/upbnding reporting
edebug
logical amr_module::edebug
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), and errf1().
eprint
logical amr_module::eprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), bufnst2(), and errf1().
errptr
integer, parameter amr_module::errptr = 3
Definition at line 41 of file amr_module.f90.
     integer, parameter :: errptr    = 3
evol
real(kind=8) amr_module::evol
Definition at line 237 of file amr_module.f90.
Referenced by amr2(), check(), prepbigstep(), prepregstep(), restrt(), and setgrd().
ffluxptr
integer, parameter amr_module::ffluxptr = 6
pointer to the address of memory storing fluxes in a layer around the grid, to be used in conservation fixup near coarse-fine grid intersections.
The memory allocated is , where is the number of its parent grid cells adjacent to (around) their boundary interfaces. The coefficient 2 is for two spaces. One is for plus or minus fluxes, and the other is for the coarse solution for wave fixing.
From node(ffluxptr,mptr) to node(ffluxptr,mptr)+lenbc-1, it stores value that should be added to the adjacent coarse cell during the synchronization for conservation fixup
From node(ffluxptr,mptr)+lenbc to node(ffluxptr,mptr)+2*lenbc-1, it stores solution q on the adjacent coarse cell
Definition at line 97 of file amr_module.f90.
Referenced by fluxsv(), outmsh(), par_advanc(), prepf(), putsp(), restrt(), saveqc(), and upbnd().
     integer, parameter :: ffluxptr  = 6
flag_gradient
logical amr_module::flag_gradient
Definition at line 258 of file amr_module.f90.
Referenced by amr2(), flagger(), and spest2().
flag_richardson
logical amr_module::flag_richardson
Definition at line 258 of file amr_module.f90.
Referenced by amr2(), bufnst2(), domain(), flagger(), restrt(), and setgrd().
     logical :: flag_richardson,flag_gradient
goodpt
real(kind=8), parameter amr_module::goodpt = 0.0
Definition at line 163 of file amr_module.f90.
Referenced by addflags(), bufnst2(), colate2(), errf1(), flagcheck(), flagger(), projec2(), setphysbndry(), and spest2().
     real(kind=8), parameter :: goodpt = 0.0
gprint
logical amr_module::gprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), colate2(), drivesort(), grdfit(), and smartbis().
gridnbor
integer, parameter amr_module::gridnbor = 1
Definition at line 158 of file amr_module.f90.
Referenced by intfil(), and makebndrylist().
     integer, parameter :: gridnbor = 1 !use 1st col, 2nd col is nextfree - the link
horizontal
integer, parameter amr_module::horizontal = 1
Definition at line 171 of file amr_module.f90.
Referenced by findcut().
     integer, parameter :: horizontal = 1
hxposs
real(kind=8), dimension(maxlv) amr_module::hxposs
Definition at line 193 of file amr_module.f90.
Referenced by advanc(), amr2(), basic(), birect(), bound(), bufnst2(), check(), conck(), domain(), errf1(), filrecur(), flagger(), gfixup(), ginit(), grdfit(), outmsh(), outval(), par_advanc(), prefilrecur(), preicall(), preintcopy(), prepbigstep(), prepc(), prepregstep(), restrt(), saveqc(), spest2(), stst1(), upbnd(), gauges_module::update_gauges(), and valout().
     real(kind=8) hxposs(maxlv), hyposs(maxlv),possk(maxlv),rnode(rsize, maxgr)
hyposs
real(kind=8), dimension(maxlv) amr_module::hyposs
Definition at line 193 of file amr_module.f90.
Referenced by advanc(), amr2(), basic(), birect(), bound(), bufnst2(), check(), conck(), domain(), errf1(), filrecur(), flagger(), gfixup(), ginit(), grdfit(), outmsh(), outval(), par_advanc(), prefilrecur(), preicall(), preintcopy(), prepbigstep(), prepc(), prepregstep(), restrt(), saveqc(), spest2(), stst1(), upbnd(), gauges_module::update_gauges(), and valout().
ibuff
integer amr_module::ibuff
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), bufnst2(), check(), colate2(), domgrid(), errest(), flagger(), freeflags(), nestck2(), projec2(), shiftset2(), and spest2().
     integer ibuff,  mstart, ndfree, ndfree_bnd, lfine, node(nsize, maxgr), &
             icheck(maxlv),lstart(maxlv),newstl(maxlv), &
             listsp(maxlv),intratx(maxlv),intraty(maxlv), &
             kratio(maxlv), iregsz(maxlv),jregsz(maxlv), &
             iregst(maxlv),jregst(maxlv), &
             iregend(maxlv),jregend(maxlv), &
             numgrids(maxlv),numcells(maxlv), &
             iorder,mxnest,kcheck
icheck
integer, dimension(maxlv) amr_module::icheck
Definition at line 198 of file amr_module.f90.
Referenced by check(), restrt(), stst1(), and tick().
iinfinity
integer, parameter amr_module::iinfinity = 999999999
Definition at line 170 of file amr_module.f90.
Referenced by amr2(), grdfit(), and tick().
     integer, parameter :: iinfinity = 999999999
intratx
integer, dimension(maxlv) amr_module::intratx
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), basecheck(), birect(), check(), domain(), domup(), filrecur(), filval(), fixcapaq(), gfixup(), grdfit(), griddomup(), nestck2(), par_advanc(), prepc(), prepf(), projec2(), putsp(), restrt(), saveqc(), setdomflags(), stst1(), tick(), and update().
intraty
integer, dimension(maxlv) amr_module::intraty
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), basecheck(), birect(), check(), domain(), domup(), filrecur(), filval(), fixcapaq(), gfixup(), grdfit(), griddomup(), nestck2(), par_advanc(), prepc(), prepf(), projec2(), putsp(), restrt(), saveqc(), setdomflags(), stst1(), tick(), and update().
inunit
integer, parameter amr_module::inunit = 5
Definition at line 289 of file amr_module.f90.
Referenced by amr2().
     integer, parameter :: inunit  = 5
iorder
integer amr_module::iorder
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), check(), errf1(), and restrt().
iout
integer amr_module::iout
Definition at line 270 of file amr_module.f90.
Referenced by amr2(), and tick().
iregend
integer, dimension(maxlv) amr_module::iregend
Definition at line 198 of file amr_module.f90.
Referenced by check(), domain(), grdfit(), outtre(), and restrt().
iregridcount
integer, dimension(maxlv) amr_module::iregridcount
Definition at line 238 of file amr_module.f90.
Referenced by amr2(), check(), domain(), regrid(), restrt(), setgrd(), and stst1().
     integer ::  iregridcount(maxlv), tvoll(maxlv)
iregst
integer, dimension(maxlv) amr_module::iregst
Definition at line 198 of file amr_module.f90.
Referenced by check(), domain(), grdfit(), outtre(), and restrt().
iregsz
integer, dimension(maxlv) amr_module::iregsz
Definition at line 198 of file amr_module.f90.
Referenced by basecheck(), check(), colate2(), domain(), drivesort(), filrecur(), filval(), grdfit(), intfil(), prefilrecur(), preicall(), preintcopy(), prepc(), projec2(), restrt(), saveqc(), setdomflags(), setindices(), setphysbndry(), setphysbndryflags(), setuse(), and sticksout().
jregend
integer, dimension(maxlv) amr_module::jregend
Definition at line 198 of file amr_module.f90.
Referenced by check(), domain(), grdfit(), outtre(), and restrt().
jregst
integer, dimension(maxlv) amr_module::jregst
Definition at line 198 of file amr_module.f90.
Referenced by check(), domain(), grdfit(), outtre(), and restrt().
jregsz
integer, dimension(maxlv) amr_module::jregsz
Definition at line 198 of file amr_module.f90.
Referenced by basecheck(), check(), colate2(), domain(), drivesort(), filrecur(), filval(), grdfit(), intfil(), prefilrecur(), preicall(), preintcopy(), prepc(), projec2(), restrt(), saveqc(), setdomflags(), setindices(), setphysbndry(), setphysbndryflags(), and sticksout().
kcheck
integer amr_module::kcheck
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), check(), restrt(), and tick().
kratio
integer, dimension(maxlv) amr_module::kratio
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), check(), domain(), restrt(), setgrd(), and tick().
lendim
integer amr_module::lendim
Definition at line 247 of file amr_module.f90.
Referenced by amr2(), check(), igetsp(), and restrt().
lenf
integer amr_module::lenf
Definition at line 225 of file amr_module.f90.
Referenced by check(), igetsp(), reclam(), restrt(), and stst1().
lenmax
integer amr_module::lenmax
Definition at line 247 of file amr_module.f90.
Referenced by amr2(), check(), igetsp(), and restrt().
lentot
integer amr_module::lentot
Definition at line 247 of file amr_module.f90.
Referenced by amr2(), check(), igetsp(), reclam(), and restrt().
     integer lentot,lenmax,lendim
levelptr
integer, parameter amr_module::levelptr = 1
node number (index) of next grid on the same level
Definition at line 35 of file amr_module.f90.
Referenced by arrangegrids(), basecheck(), basic(), birect(), cleanup(), colate2(), conck(), domain(), domgrid(), domprep(), freeflags(), gfixup(), ginit(), grdfit(), icall(), intcopy(), intfil(), makegridlist(), outlev(), outmsh(), outtre(), prepc(), prepf(), prepgrids(), prepnewgrids(), projec2(), putsp(), regrid(), restrt(), saveqc(), gauges_module::setbestsrc(), setdomflags(), setgrd(), update(), and valout().
     integer, parameter :: levelptr  = 1
lfdim
integer, parameter amr_module::lfdim =5000
Definition at line 224 of file amr_module.f90.
Referenced by check(), reclam(), restrt(), and stst1().
     integer, parameter :: lfdim=5000
lfine
integer amr_module::lfine
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), basic(), check(), cleanup(), domain(), gfixup(), makegridlist(), nodget(), nodget_bnd(), outtre(), putsp(), regrid(), restrt(), gauges_module::setbestsrc(), setgrd(), stst1(), tick(), and valout().
lfree
integer, dimension(lfdim,2) amr_module::lfree
Definition at line 225 of file amr_module.f90.
Referenced by check(), igetsp(), reclam(), restrt(), and stst1().
     integer lfree(lfdim,2),lenf
listofgrids
integer, dimension(maxgr) amr_module::listofgrids
Definition at line 189 of file amr_module.f90.
Referenced by advanc(), bufnst2(), flagger(), intfil(), makebndrylist(), makegridlist(), and update().
     integer :: listofgrids(maxgr),liststart(0:maxlv+1)
listsp
integer, dimension(maxlv) amr_module::listsp
Definition at line 198 of file amr_module.f90.
Referenced by check(), par_advanc(), prepc(), putsp(), restrt(), and update().
liststart
integer, dimension(0:maxlv+1) amr_module::liststart
Definition at line 189 of file amr_module.f90.
Referenced by advanc(), bufnst2(), domain(), flagger(), intfil(), makebndrylist(), makegridlist(), restrt(), and update().
lstart
integer, dimension(maxlv) amr_module::lstart
Definition at line 198 of file amr_module.f90.
Referenced by advanc(), arrangegrids(), basecheck(), basic(), bufnst2(), check(), cleanup(), colate2(), conck(), domain(), domgrid(), domprep(), freeflags(), gfixup(), icall(), intcopy(), intfil(), makegridlist(), outtre(), prepc(), prepf(), prepgrids(), putsp(), regrid(), restrt(), saveqc(), gauges_module::setbestsrc(), setdomflags(), setgrd(), stst1(), tick(), update(), and valout().
matlabout
logical amr_module::matlabout
Definition at line 264 of file amr_module.f90.
matlabu
integer amr_module::matlabu
Definition at line 283 of file amr_module.f90.
Referenced by amr2(), check(), restrt(), and valout().
     integer :: matlabu
matunit
integer, parameter amr_module::matunit = 70
Definition at line 294 of file amr_module.f90.
Referenced by amr2().
     integer, parameter :: matunit = 70
max1d
integer, parameter amr_module::max1d = 60
Definition at line 181 of file amr_module.f90.
Referenced by amr2(), birect(), qad(), saveqc(), stepgrid(), and stepgrid_dimsplit().
     integer, parameter :: max1d = 60
maxaux
integer, parameter amr_module::maxaux = 20
Definition at line 184 of file amr_module.f90.
Referenced by qad(), stepgrid(), stepgrid_dimsplit(), and gauges_module::update_gauges().
     integer, parameter :: maxaux = 20
maxcl
integer, parameter amr_module::maxcl = 5000
maximum number of clusters (grids) on each grid level
Definition at line 177 of file amr_module.f90.
Referenced by grdfit(), nestck2(), and smartbis().
     integer, parameter :: maxcl = 5000
maxgr
integer, parameter amr_module::maxgr = 15000
Definition at line 173 of file amr_module.f90.
Referenced by check(), nodget(), restrt(), gauges_module::set_gauges(), and stst1().
     integer, parameter :: maxgr = 15000
maxlv
integer, parameter amr_module::maxlv = 10
Definition at line 174 of file amr_module.f90.
Referenced by amr2(), check(), restrt(), stst1(), and tick().
     integer, parameter :: maxlv = 10
maxvar
integer, parameter amr_module::maxvar = 10
Definition at line 183 of file amr_module.f90.
Referenced by amr2(), stepgrid(), stepgrid_dimsplit(), and gauges_module::update_gauges().
     integer, parameter :: maxvar = 10
maxwave
integer, parameter amr_module::maxwave = 10
Definition at line 185 of file amr_module.f90.
     integer, parameter :: maxwave = 10
mcapa
integer amr_module::mcapa
Definition at line 253 of file amr_module.f90.
Referenced by amr2(), conck(), filval(), fixcapaq(), step2(), step2x(), step2y(), stepgrid(), stepgrid_dimsplit(), upbnd(), and update().
memsize
integer amr_module::memsize
Definition at line 219 of file amr_module.f90.
Referenced by check(), igetsp(), init_alloc(), resize_storage(), restrt(), restrt_alloc(), and stst1().
     integer memsize
method
integer, dimension(7) amr_module::method
Definition at line 253 of file amr_module.f90.
Referenced by amr2(), flux2(), flux2_dimsplit(), qad(), regrid(), setgrd(), stepgrid(), stepgrid_dimsplit(), and tick().
     integer  method(7), mwaves, mcapa, dimensional_split
mstart
integer amr_module::mstart
Definition at line 198 of file amr_module.f90.
Referenced by amr2(), check(), domain(), nestck2(), restrt(), and tick().
mthbc
integer, dimension(4) amr_module::mthbc
Definition at line 232 of file amr_module.f90.
Referenced by amr2(), and bc2amr().
mthlim
integer, dimension(:), allocatable amr_module::mthlim
Definition at line 254 of file amr_module.f90.
Referenced by amr2(), flux2(), flux2_dimsplit(), and limiter().
     integer, allocatable :: mthlim(:)
mwaves
integer amr_module::mwaves
Definition at line 253 of file amr_module.f90.
Referenced by amr2(), flux2(), flux2_dimsplit(), limiter(), and qad().
mxnest
integer amr_module::mxnest
Definition at line 198 of file amr_module.f90.
Referenced by advanc(), amr2(), bufnst2(), check(), cleanup(), domain(), gfixup(), ginit(), intfil(), par_advanc(), regrid(), restrt(), setgrd(), stst1(), and tick().
naux_components
integer amr_module::naux_components
Definition at line 274 of file amr_module.f90.
ncarout
logical amr_module::ncarout
Definition at line 264 of file amr_module.f90.
nchkpt
integer amr_module::nchkpt
Definition at line 280 of file amr_module.f90.
Referenced by amr2(), and tick().
ndfree
integer amr_module::ndfree
Definition at line 198 of file amr_module.f90.
Referenced by check(), nodget(), putnod(), restrt(), and stst1().
ndfree_bnd
integer amr_module::ndfree_bnd
Definition at line 198 of file amr_module.f90.
Referenced by check(), initbndrylist(), nodget_bnd(), putnod_bnd(), and restrt().
ndihi
integer, parameter amr_module::ndihi = 10
global i index of right border of this grid
Definition at line 111 of file amr_module.f90.
Referenced by advanc(), arrangegrids(), basecheck(), birect(), bound(), bufnst2(), cleanup(), colate2(), conck(), domain(), domgrid(), domprep(), flagger(), fluxsv(), freeflags(), gfixup(), ginit(), grdfit(), icall(), intcopy(), intfil(), makebndrylist(), moment(), nestck2(), outmsh(), par_advanc(), prepc(), prepf(), projec2(), putsp(), regrid(), restrt(), saveqc(), setdomflags(), setgrd(), spest2(), update(), and valout().
     integer, parameter :: ndihi     = 10
ndilo
integer, parameter amr_module::ndilo = 9
global i index of left border of this grid
Definition at line 108 of file amr_module.f90.
Referenced by advanc(), arrangegrids(), basecheck(), birect(), bound(), bufnst2(), cleanup(), colate2(), conck(), domain(), domgrid(), domprep(), flagger(), fluxsv(), freeflags(), gfixup(), ginit(), grdfit(), icall(), intcopy(), intfil(), makebndrylist(), moment(), nestck2(), outmsh(), par_advanc(), prepc(), prepf(), projec2(), putsp(), regrid(), restrt(), saveqc(), setdomflags(), setflags(), setgrd(), spest2(), update(), and valout().
     integer, parameter :: ndilo     = 9
ndjhi
integer, parameter amr_module::ndjhi = 12
global j index of upper border of this grid
Definition at line 117 of file amr_module.f90.
Referenced by advanc(), arrangegrids(), basecheck(), birect(), bound(), bufnst2(), cleanup(), colate2(), conck(), domain(), domgrid(), domprep(), flagger(), fluxsv(), freeflags(), gfixup(), ginit(), grdfit(), icall(), intcopy(), intfil(), makebndrylist(), moment(), nestck2(), outmsh(), par_advanc(), prepc(), prepf(), projec2(), putsp(), regrid(), restrt(), saveqc(), setdomflags(), setgrd(), spest2(), update(), and valout().
     integer, parameter :: ndjhi     = 12
ndjlo
integer, parameter amr_module::ndjlo = 11
global j index of lower border of this grid
Definition at line 114 of file amr_module.f90.
Referenced by advanc(), arrangegrids(), basecheck(), birect(), bound(), bufnst2(), cleanup(), colate2(), conck(), domain(), domgrid(), domprep(), flagger(), fluxsv(), freeflags(), gfixup(), ginit(), grdfit(), icall(), intcopy(), intfil(), makebndrylist(), moment(), nestck2(), outmsh(), par_advanc(), prepc(), prepf(), projec2(), putsp(), regrid(), restrt(), saveqc(), setdomflags(), setflags(), setgrd(), spest2(), update(), and valout().
     integer, parameter :: ndjlo     = 11
needs_to_be_set
real(kind=8), parameter amr_module::needs_to_be_set = 10.e33
Definition at line 168 of file amr_module.f90.
Referenced by filrecur(), filval(), fixcapaq(), ginit(), prefilrecur(), preicall(), prepbigstep(), and saveqc().
     real(kind=8), parameter :: needs_to_be_set = 10.e33
nestlevel
integer, parameter amr_module::nestlevel = 4
AMR level of the grid.
Definition at line 44 of file amr_module.f90.
Referenced by basecheck(), birect(), bound(), domain(), errf1(), flagcheck(), fluxsv(), ginit(), grdfit(), nestck2(), outmsh(), outtre(), outval(), par_advanc(), qad(), setuse(), upbnd(), and gauges_module::update_gauges().
     integer, parameter :: nestlevel = 4
newstl
integer, dimension(maxlv) amr_module::newstl
Definition at line 198 of file amr_module.f90.
Referenced by check(), filval(), gfixup(), grdfit(), prepnewgrids(), projec2(), regrid(), restrt(), and setgrd().
nextfree
integer, parameter amr_module::nextfree = 2
Definition at line 154 of file amr_module.f90.
Referenced by freebndrylist(), initbndrylist(), intfil(), makebndrylist(), nodget(), nodget_bnd(), putnod(), putnod_bnd(), and stst1().
     integer, parameter :: nextfree = 2
nghost
integer amr_module::nghost
Definition at line 232 of file amr_module.f90.
Referenced by addflags(), advanc(), amr2(), basic(), birect(), bufnst2(), cleanup(), colate2(), conck(), domain(), domgrid(), errest(), errf1(), filrecur(), filval(), fixcapaq(), flagger(), freeflags(), gfixup(), ginit(), icall(), intcopy(), intfil(), makebndrylist(), nestck2(), outmsh(), outval(), par_advanc(), prefilrecur(), preicall(), preintcopy(), prepbigstep(), prepregstep(), qad(), restrt(), saveqc(), setflags(), setuse(), spest2(), update(), gauges_module::update_gauges(), and valout().
     integer :: nghost, mthbc(4)
nil
integer, parameter amr_module::nil = 0
Definition at line 156 of file amr_module.f90.
     integer, parameter :: nil  = 0
node
integer, dimension(nsize, maxgr) amr_module::node
Definition at line 198 of file amr_module.f90.
Referenced by advanc(), arrangegrids(), basecheck(), basic(), birect(), bound(), bufnst2(), check(), cleanup(), colate2(), conck(), domain(), domgrid(), domprep(), errest(), errf1(), flagcheck(), flagger(), fluxsv(), freebndrylist(), freeflags(), gfixup(), ginit(), grdfit(), icall(), intcopy(), intfil(), makebndrylist(), makegridlist(), moment(), nestck2(), nodget(), nodget_bnd(), outlev(), outmsh(), outtre(), outval(), par_advanc(), prepbigstep(), prepc(), prepf(), prepgrids(), prepnewgrids(), projec2(), putnod(), putsp(), qad(), regrid(), restrt(), saveqc(), gauges_module::setbestsrc(), setdomflags(), setflags(), setgrd(), setuse(), spest2(), stst1(), upbnd(), update(), gauges_module::update_gauges(), and valout().
nout
integer amr_module::nout
Definition at line 270 of file amr_module.f90.
Referenced by amr2(), and tick().
nprint
logical amr_module::nprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), flagcheck(), and nestck2().
nq_components
integer amr_module::nq_components
Definition at line 274 of file amr_module.f90.
     integer :: nq_components, naux_components, output_format
nsize
integer, parameter amr_module::nsize = 19
Definition at line 31 of file amr_module.f90.
Referenced by basic(), grdfit(), moment(), nodget(), and smartbis().
     integer, parameter :: nsize = 19
nstop
integer amr_module::nstop
Definition at line 270 of file amr_module.f90.
Referenced by amr2(), and tick().
null
integer, parameter amr_module::null = 0
Definition at line 155 of file amr_module.f90.
Referenced by advanc(), arrangegrids(), grdfit(), initbndrylist(), nodget(), nodget_bnd(), and stst1().
     integer, parameter :: null = 0
numcells
integer, dimension(maxlv) amr_module::numcells
Definition at line 198 of file amr_module.f90.
Referenced by domain(), regrid(), setgrd(), and stst1().
numflags
integer, parameter amr_module::numflags = 15
number of flagged cells on this grid
Definition at line 126 of file amr_module.f90.
Referenced by bufnst2(), and colate2().
     integer, parameter :: numflags  = 15
numgrids
integer, dimension(maxlv) amr_module::numgrids
Definition at line 198 of file amr_module.f90.
Referenced by advanc(), amr2(), bufnst2(), check(), domain(), flagger(), intfil(), makebndrylist(), makegridlist(), nodget(), nodget_bnd(), outtre(), regrid(), restrt(), setgrd(), spest2(), stst1(), and update().
output_aux_components
integer, dimension(:), allocatable amr_module::output_aux_components
Definition at line 276 of file amr_module.f90.
Referenced by amr2(), and valout().
     integer, allocatable :: output_aux_components(:)
output_aux_onlyonce
logical amr_module::output_aux_onlyonce
Definition at line 277 of file amr_module.f90.
Referenced by amr2(), and valout().
     logical :: output_aux_onlyonce
output_format
integer amr_module::output_format
Definition at line 274 of file amr_module.f90.
Referenced by amr2(), and valout().
output_q_components
integer, dimension(:), allocatable amr_module::output_q_components
Definition at line 275 of file amr_module.f90.
Referenced by amr2().
     integer, allocatable :: output_q_components(:)
output_style
integer amr_module::output_style
Definition at line 270 of file amr_module.f90.
Referenced by amr2().
     integer :: output_style, nstop, nout, iout
outunit
integer, parameter amr_module::outunit = 66
Definition at line 290 of file amr_module.f90.
Referenced by amr2(), bufnst2(), check(), colate2(), conck(), domain(), domcopy(), domprep(), domshrink(), domup(), drivesort(), errf1(), filrecur(), filval(), flagcheck(), grdfit(), griddomshrink(), griddomup(), igetsp(), intfil(), nestck2(), nodget(), nodget_bnd(), outlev(), outmsh(), outtre(), outval(), projec2(), reclam(), regrid(), restrt(), smartbis(), stepgrid(), stepgrid_dimsplit(), tick(), upbnd(), and update().
     integer, parameter :: outunit = 66
parmunit
integer, parameter amr_module::parmunit = 12
Definition at line 287 of file amr_module.f90.
Referenced by amr2(), and regions_module::set_regions().
     integer, parameter :: parmunit = 12
pltunit1
integer, parameter amr_module::pltunit1 = 3
Definition at line 291 of file amr_module.f90.
Referenced by basic(), and outvar().
     integer, parameter :: pltunit1 = 3
possk
real(kind=8), dimension(maxlv) amr_module::possk
Definition at line 193 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), conck(), domain(), errf1(), flagger(), intfil(), outmsh(), par_advanc(), prepbigstep(), prepregstep(), restrt(), setgrd(), spest2(), tick(), and update().
pprint
logical amr_module::pprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), and projec2().
printout
logical amr_module::printout
Definition at line 264 of file amr_module.f90.
Referenced by amr2(), and tick().
     logical    printout,matlabout,ncarout
rinfinity
real(kind=8), parameter amr_module::rinfinity = 10.e32
Definition at line 169 of file amr_module.f90.
Referenced by advanc(), amr2(), stepgrid(), stepgrid_dimsplit(), and tick().
     real(kind=8), parameter :: rinfinity = 10.e32
rnode
real(kind=8), dimension(rsize, maxgr) amr_module::rnode
Definition at line 193 of file amr_module.f90.
Referenced by advanc(), basic(), birect(), bound(), bufnst2(), check(), domain(), errf1(), flagger(), gfixup(), ginit(), grdfit(), intfil(), moment(), nestck2(), nodget(), outmsh(), outval(), par_advanc(), prepbigstep(), prepregstep(), qad(), regrid(), restrt(), saveqc(), gauges_module::setbestsrc(), setgrd(), spest2(), gauges_module::update_gauges(), and valout().
rprint
logical amr_module::rprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), and tick().
rsize
integer, parameter amr_module::rsize = 5
Definition at line 30 of file amr_module.f90.
Referenced by basic(), check(), grdfit(), nodget(), and restrt().
     integer, parameter :: rsize = 5
rstfile
character(len=200) amr_module::rstfile
Definition at line 311 of file amr_module.f90.
Referenced by amr2(), and restrt().
     character(len=200) :: rstfile
rstunit
integer, parameter amr_module::rstunit = 9
Definition at line 292 of file amr_module.f90.
Referenced by restrt().
     integer, parameter :: rstunit = 9
rvol
real(kind=8) amr_module::rvol
Definition at line 237 of file amr_module.f90.
Referenced by amr2(), check(), par_advanc(), restrt(), and setgrd().
rvoll
real(kind=8), dimension(maxlv) amr_module::rvoll
Definition at line 237 of file amr_module.f90.
Referenced by amr2(), check(), par_advanc(), restrt(), and setgrd().
     real(kind=8)  rvoll(maxlv),evol,rvol,avenumgrids(maxlv)
spheredom
logical amr_module::spheredom
Definition at line 230 of file amr_module.f90.
Referenced by amr2(), bc2amr(), bound(), domcopy(), domprep(), domup(), filrecur(), filval(), prefilrecur(), preicall(), preintcopy(), prepc(), projec2(), and saveqc().
sprint
logical amr_module::sprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), igetsp(), and reclam().
store1
integer, parameter amr_module::store1 = 7
pointer to the address of memory storing the first copy of solution data on this grid, usually for storing new solution
Definition at line 101 of file amr_module.f90.
Referenced by advanc(), cleanup(), conck(), domain(), errest(), flagger(), gfixup(), ginit(), icall(), intcopy(), intfil(), outmsh(), par_advanc(), restrt(), setgrd(), spest2(), update(), and valout().
     integer, parameter :: store1    = 7
store2
integer, parameter amr_module::store2 = 8
pointer to the address of memory storing the second copy of solution data on this grid, usually for storing old solution
Definition at line 105 of file amr_module.f90.
Referenced by cleanup(), errest(), flagger(), gfixup(), ginit(), intfil(), outmsh(), par_advanc(), prepbigstep(), restrt(), setgrd(), and spest2().
     integer, parameter :: store2    = 8
storeaux
integer, parameter amr_module::storeaux = 13
pointer to the address of memory storing auxiliary data on this grid
Definition at line 120 of file amr_module.f90.
Referenced by advanc(), cleanup(), conck(), domain(), errest(), flagger(), gfixup(), ginit(), icall(), outmsh(), par_advanc(), restrt(), saveqc(), spest2(), upbnd(), update(), and valout().
     integer, parameter :: storeaux  = 13
storeflags
integer, parameter amr_module::storeflags = 14
pointer to the address of memory storing flags for refinement on this grid
Definition at line 123 of file amr_module.f90.
Referenced by bufnst2(), colate2(), errest(), flagger(), freeflags(), and spest2().
     integer, parameter :: storeflags  = 14
t0
real(kind=8) amr_module::t0
Definition at line 272 of file amr_module.f90.
Referenced by amr2(), conck(), and valout().
     real(kind=8) :: t0, tfinal
tchk
real(kind=8), dimension(:), allocatable amr_module::tchk
Definition at line 281 of file amr_module.f90.
Referenced by amr2(), and tick().
     real(kind=8), allocatable :: tchk(:)
tempptr
integer, parameter amr_module::tempptr = 2
temporary pointer
Definition at line 38 of file amr_module.f90.
Referenced by bufnst2(), errest(), flagger(), and spest2().
     integer, parameter :: tempptr   = 2
tfinal
real(kind=8) amr_module::tfinal
Definition at line 272 of file amr_module.f90.
Referenced by amr2(), and tick().
timebound
integer amr_module::timebound
Definition at line 241 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), inittimers(), and restrt().
     integer :: timebound,timestepgrid
timeboundcpu
real(kind=8) amr_module::timeboundcpu
Definition at line 244 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), inittimers(), and restrt().
     real(kind=8) timeboundcpu,timestepgridcpu,timeregriddingcpu
timebufnst
integer amr_module::timebufnst
Definition at line 242 of file amr_module.f90.
Referenced by amr2(), flglvl2(), initrestoftimers(), and inittimers().
timeflagger
integer amr_module::timeflagger
Definition at line 242 of file amr_module.f90.
Referenced by amr2(), flglvl2(), initrestoftimers(), and inittimers().
     integer :: timeflagger, timebufnst,timetick
timeflglvl
integer amr_module::timeflglvl
Definition at line 240 of file amr_module.f90.
Referenced by grdfit(), initrestoftimers(), and inittimers().
     integer :: timeflglvl,timegrdfit2,timegrdfit3,timegrdfitall
timegrdfit2
integer amr_module::timegrdfit2
Definition at line 240 of file amr_module.f90.
Referenced by initrestoftimers(), inittimers(), and regrid().
timegrdfit3
integer amr_module::timegrdfit3
Definition at line 240 of file amr_module.f90.
timegrdfitall
integer amr_module::timegrdfitall
Definition at line 240 of file amr_module.f90.
Referenced by grdfit(), and inittimers().
timemult
integer, parameter amr_module::timemult = 5
current simulation time on this grid
Definition at line 151 of file amr_module.f90.
Referenced by advanc(), birect(), bufnst2(), errf1(), flagger(), gfixup(), ginit(), grdfit(), intfil(), outmsh(), par_advanc(), prepbigstep(), prepregstep(), qad(), regrid(), saveqc(), setgrd(), spest2(), and gauges_module::update_gauges().
     integer, parameter :: timemult = 5
timeregridding
integer amr_module::timeregridding
Definition at line 239 of file amr_module.f90.
Referenced by amr2(), check(), inittimers(), restrt(), and tick().
     integer :: timeregridding, timeupdating, timevalout
timeregriddingcpu
real(kind=8) amr_module::timeregriddingcpu
Definition at line 244 of file amr_module.f90.
Referenced by amr2(), check(), inittimers(), restrt(), and tick().
timestepgrid
integer amr_module::timestepgrid
Definition at line 241 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), inittimers(), and restrt().
timestepgridcpu
real(kind=8) amr_module::timestepgridcpu
Definition at line 244 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), inittimers(), and restrt().
timetick
integer amr_module::timetick
Definition at line 242 of file amr_module.f90.
Referenced by amr2(), check(), inittimers(), restrt(), and tick().
timetickcpu
real(kind=8) amr_module::timetickcpu
Definition at line 243 of file amr_module.f90.
Referenced by amr2(), check(), inittimers(), restrt(), and tick().
timeupdating
integer amr_module::timeupdating
Definition at line 239 of file amr_module.f90.
Referenced by amr2(), initrestoftimers(), inittimers(), and tick().
timevalout
integer amr_module::timevalout
Definition at line 239 of file amr_module.f90.
Referenced by amr2(), check(), inittimers(), restrt(), and valout().
timevaloutcpu
real(kind=8) amr_module::timevaloutcpu
Definition at line 245 of file amr_module.f90.
Referenced by amr2(), check(), inittimers(), restrt(), and valout().
     real(kind=8) timevaloutcpu
tmass0
real(kind=8) amr_module::tmass0
Definition at line 267 of file amr_module.f90.
Referenced by check(), conck(), and restrt().
     real(kind=8) tmass0
tol
real(kind=8) amr_module::tol
Definition at line 197 of file amr_module.f90.
Referenced by amr2(), check(), and errf1().
     real(kind=8) tol, tolsp
tolsp
real(kind=8) amr_module::tolsp
Definition at line 197 of file amr_module.f90.
Referenced by amr2(), flagger(), and spest2().
tout
real(kind=8), dimension(:), allocatable amr_module::tout
Definition at line 271 of file amr_module.f90.
Referenced by amr2(), and tick().
     real(kind=8), allocatable :: tout(:)
tprint
logical amr_module::tprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), and tick().
tstart_thisrun
real(kind=8) amr_module::tstart_thisrun
Definition at line 273 of file amr_module.f90.
Referenced by amr2().
     real(kind=8) :: tstart_thisrun  ! /= t0 in case of restart
tvoll
integer, dimension(maxlv) amr_module::tvoll
Definition at line 238 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), restrt(), and stst1().
tvollcpu
real(kind=8), dimension(maxlv) amr_module::tvollcpu
Definition at line 243 of file amr_module.f90.
Referenced by advanc(), amr2(), check(), and restrt().
     real(kind=8) tvollcpu(maxlv), timetickcpu
uprint
logical amr_module::uprint
Definition at line 297 of file amr_module.f90.
Referenced by amr2(), upbnd(), and update().
use_fwaves
logical amr_module::use_fwaves
Definition at line 257 of file amr_module.f90.
Referenced by amr2(), flux2(), and flux2_dimsplit().
     logical :: use_fwaves
verbosity_regrid
integer amr_module::verbosity_regrid
Definition at line 259 of file amr_module.f90.
Referenced by amr2(), bufnst2(), regrid(), setgrd(), and tick().
     integer :: verbosity_regrid
vertical
integer, parameter amr_module::vertical = 2
Definition at line 172 of file amr_module.f90.
Referenced by findcut(), and smartbis().
     integer, parameter :: vertical = 2
xlower
real(kind=8) amr_module::xlower
Definition at line 231 of file amr_module.f90.
Referenced by amr2(), basic(), bc2amr(), bound(), domain(), filrecur(), filval(), grdfit(), prefilrecur(), preicall(), and preintcopy().
xperdom
logical amr_module::xperdom
Definition at line 230 of file amr_module.f90.
Referenced by amr2(), basecheck(), bc2amr(), bound(), colate2(), domcopy(), domprep(), domshrink(), domup(), filrecur(), filval(), prefilrecur(), preicall(), preintcopy(), prepc(), projec2(), saveqc(), setdomflags(), setindices(), setphysbndry(), and setphysbndryflags().
     logical xperdom, yperdom, spheredom
xupper
real(kind=8) amr_module::xupper
Definition at line 231 of file amr_module.f90.
Referenced by amr2(), basic(), bc2amr(), bound(), domain(), filrecur(), and filval().
     real(kind=8) :: xupper, yupper, xlower, ylower
ylower
real(kind=8) amr_module::ylower
Definition at line 231 of file amr_module.f90.
Referenced by amr2(), basic(), bc2amr(), bound(), domain(), filrecur(), filval(), grdfit(), prefilrecur(), preicall(), and preintcopy().
yperdom
logical amr_module::yperdom
Definition at line 230 of file amr_module.f90.
Referenced by amr2(), basecheck(), bc2amr(), bound(), colate2(), domcopy(), domprep(), domshrink(), domup(), filrecur(), filval(), prefilrecur(), preicall(), preintcopy(), prepc(), projec2(), saveqc(), setdomflags(), setindices(), setphysbndry(), and setphysbndryflags().
yupper
real(kind=8) amr_module::yupper
Definition at line 231 of file amr_module.f90.
Referenced by amr2(), basic(), bc2amr(), bound(), domain(), filrecur(), and filval().