2D AMRCLAW: regions_module Module Reference
regions_module Module Reference
Data Types
type region_type
Functions/Subroutines
subroutine set_regions (fname)
Variables
logical, private module_setup
integer num_regions
type(region_type), dimension(:), allocatable regions
Function/Subroutine Documentation
set_regions()
subroutine regions_module::set_regions (character(len=*), intent(in), optional fname)
Definition at line 25 of file regions_module.f90.
References module_setup, num_regions, opendatafile(), amr_module::parmunit, and regions.
Referenced by amr2().
         use amr_module
         implicit none
         ! Function Arguments
         character(len=*), optional, intent(in) :: fname
         ! Locals
         integer, parameter :: unit = 7
         integer :: i
         if (.not. module_setup) then
             write(parmunit,*) ' '
             write(parmunit,*) '--------------------------------------------'
             write(parmunit,*) 'REGIONS:'
             write(parmunit,*) '-----------'
             if (present(fname)) then
                 call opendatafile(unit,fname)
             else
                 call opendatafile(unit,'regions.data')
             endif
             read(unit,"(i2)") num_regions
             if (num_regions == 0) then
                 write(parmunit,*) '  No regions specified for refinement'
             else
                 ! Refinement region data
                 allocate(regions(num_regions))
                 do i=1,num_regions
                     read(unit,*) regions(i)%min_level, regions(i)%max_level, &
                                  regions(i)%t_low, regions(i)%t_hi, &
                                  regions(i)%x_low, regions(i)%x_hi, &
                                  regions(i)%y_low, regions(i)%y_hi
                 enddo
             endif
             close(unit)
             module_setup = .true.
         end if
Variable Documentation
module_setup
logical, private regions_module::module_setup private
Definition at line 17 of file regions_module.f90.
Referenced by set_regions().
     logical, private :: module_setup
num_regions
integer regions_module::num_regions
Definition at line 19 of file regions_module.f90.
Referenced by flagregions(), flagregions2(), and set_regions().
     integer :: num_regions
regions
type(region_type), dimension(:), allocatable regions_module::regions
Definition at line 20 of file regions_module.f90.
Referenced by flagregions(), flagregions2(), and set_regions().
     type(region_type), allocatable :: regions(:)