2D AMRCLAW: outtre.f File Reference
outtre.f File Reference
Functions/Subroutines
subroutine outtre (mlev, outgrd, nvar, naux)
Output a subtree of the grids.
subroutine outlev (mlev, outgrd, nvar, naux)
Output all grids on the same level as grid mlev.
Function/Subroutine Documentation
outlev()
subroutine outlev (mlev, logical outgrd, nvar, naux)
Output all grids on the same level as grid mlev.
Parameters
[in] mlev representative grid of the grid level being output
[in] outgrd If true, output value on grid
[in] nvar number of equations for the system
[in] naux number of auxiliary variables
Definition at line 55 of file outtre.f.
References amr_module::levelptr, amr_module::node, outmsh(), and amr_module::outunit.
 c
       use amr_module
       implicit double precision (a-h,o-z)
       logical  outgrd
 c
 c ::::::::::::::::::::::: OUTTRE :::::::::::::::::::::::::::::::::::
 c
 c outtre - output subtree
 c input parameters:
 c    mlev   - ptr to subtree to output i.e., start at level(mlev)
 c    outgrd - if true, output the values on the grid
 c tree is output from 'level' to finest level.
 c
 c :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 c
       write (outunit,1)
 1     format(1x,"the partially built new subtree is:")
 c
           mptr = mlev
  20       if (mptr .eq. 0) go to 30
               call outmsh(mptr,outgrd,nvar,naux)
               mptr = node(levelptr, mptr)
           go to 20
  30       continue
 c
  99   return
outtre()
subroutine outtre (mlev, logical outgrd, nvar, naux)
Output a subtree of the grids.
All grids from the grid level of grid mlev to the finest level are output.
Parameters
[in] mlev root grid for current output.
[in] outgrd If true, output value on grid
[in] nvar number of equations for the system
[in] naux number of auxiliary variables
Definition at line 11 of file outtre.f.
References amr_module::iregend, amr_module::iregst, amr_module::jregend, amr_module::jregst, amr_module::levelptr, amr_module::lfine, amr_module::lstart, amr_module::nestlevel, amr_module::node, amr_module::numgrids, outmsh(), and amr_module::outunit.
Referenced by amr2(), intfil(), nestck2(), and tick().
 c
       use amr_module
       implicit double precision (a-h,o-z)
       logical  outgrd
 c
 c ::::::::::::::::::::::: OUTTRE :::::::::::::::::::::::::::::::::::
 c
 c outtre - output subtree
 c input parameters:
 c    mlev   - ptr to subtree to output i.e., start at level(mlev)
 c    outgrd - if true, output the values on the grid
 c tree is output from 'level' to finest level.
 c
 c :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 c
       write (outunit,1)
 1     format(1x,14hthe subtree is)
 c
       level = node(nestlevel, mlev)
 10    if (level .gt. lfine) go to 99
           mptr    = lstart(level)
  20       if (mptr .eq. 0) go to 30
               call outmsh(mptr,outgrd,nvar,naux)
               mptr = node(levelptr, mptr)
           go to 20
  30       continue
           write(outunit,2) numgrids(level), level,iregst(level),
      1                     jregst(level),iregend(level),jregend(level)
  2        format(/,i5," grids at level ",i5," go from ",2i9," to",2i9,/)
           level = level + 1
       go to 10
 c
  99   return