2D AMRCLAW: putnod.f File Reference
putnod.f File Reference
Functions/Subroutines
subroutine putnod (mptr)
subroutine putnod_bnd (mcell)
Function/Subroutine Documentation
putnod()
subroutine putnod (mptr)
Definition at line 5 of file putnod.f.
References amr_module::ndfree, amr_module::nextfree, and amr_module::node.
Referenced by gfixup(), and restrt().
 c
       use amr_module
       implicit double precision (a-h,o-z)
 c :::::::::::::::::::::::::::::: PUTNOD :::::::::::::::::::::;
 c
 c  return mptr node to the linked list kept in node array.
 c
 c ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;
 c
       node(nextfree, mptr) = ndfree
       ndfree               = mptr
 c
       return
putnod_bnd()
subroutine putnod_bnd (mcell)
Definition at line 25 of file putnod.f.
References amr_module::bndlist, amr_module::ndfree_bnd, and amr_module::nextfree.
Referenced by freebndrylist().
 c
       use amr_module
       implicit double precision (a-h,o-z)
 c :::::::::::::::::::::::::::::: PUTNOD_BND :::::::::::::::::::::;
 c
 c  return bndry list node to the linked list
 c
 c ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;
 c
       bndlist(mcell, nextfree) = ndfree_bnd
       ndfree_bnd               = mcell
 c
       return