2D AMRCLAW: rpn2from1d.f File Reference
rpn2from1d.f File Reference
Functions/Subroutines
subroutine rpn2 (ixy, maxm, meqn, mwaves, maux, mbc, mx, ql, qr, auxl, auxr, wave, s, amdq, apdq)
Function/Subroutine Documentation
rpn2()
subroutine rpn2 (ixy, maxm, meqn, mwaves, maux, mbc, mx, dimension(meqn, 1-mbc:maxm+mbc) ql, dimension(meqn, 1-mbc:maxm+mbc) qr, auxl, auxr, dimension(meqn, mwaves, 1-mbc:maxm+mbc) wave, dimension(mwaves, 1-mbc:maxm+mbc) s, dimension(meqn, 1-mbc:maxm+mbc) amdq, dimension(meqn, 1-mbc:maxm+mbc) apdq)
Definition at line 7 of file rpn2from1d.f.
Referenced by flux2(), flux2_dimsplit(), qad(), step2(), step2x(), step2y(), stepgrid(), and stepgrid_dimsplit().
 c     =====================================================
 c
 c     # Solve Riemann problems for the 2D hyperbolic problem.
 c
 c     # This is a wrapper for a 1d Riemann solver rp1 so that it
 c     # can be used with AMR by using the 2d amrclaw routines with my=1.
 c
       implicit double precision (a-h,o-z)
 c
       dimension wave(meqn, mwaves, 1-mbc:maxm+mbc)
       dimension    s(mwaves, 1-mbc:maxm+mbc)
       dimension   ql(meqn, 1-mbc:maxm+mbc)
       dimension   qr(meqn, 1-mbc:maxm+mbc)
       dimension  apdq(meqn, 1-mbc:maxm+mbc)
       dimension  amdq(meqn, 1-mbc:maxm+mbc)
 c
       if (ixy.eq.2) then
 c        write(6,*) '*** Error, this Riemann solver should only be used'
 c        write(6,*) '*** for a 1d problem with my=1'
 c        write(6,*) '*** ixy=2 and my = ',mx
 c        stop
          endif
       call rp1(maxm,meqn,mwaves,maux,mbc,mx,ql,qr,auxl,auxr,
      &                  wave,s,amdq,apdq)
       return