2D AMRCLAW: setaux.f90 File Reference
setaux.f90 File Reference
Functions/Subroutines
subroutine setaux (mbc, mx, my, xlower, ylower, dx, dy, maux, aux)
Function/Subroutine Documentation
setaux()
subroutine setaux (integer, intent(in) mbc, integer, intent(in) mx, integer, intent(in) my, real(kind=8), intent(in) xlower, real(kind=8), intent(in) ylower, real(kind=8), intent(in) dx, real(kind=8), intent(in) dy, integer, intent(in) maux, real(kind=8), dimension(maux,1-mbc:mx+mbc,1-mbc:my+mbc), intent(inout) aux)
Definition at line 2 of file setaux.f90.
Referenced by filrecur(), filval(), ginit(), prefilrecur(), preicall(), prepbigstep(), and saveqc().
     ! Called at start of computation before calling qinit, and
     ! when AMR is used, also called every time a new grid patch is created.
     ! Use to set auxiliary arrays aux(1:maux, 1-mbc:mx+mbc, 1-mbc:my+mbc).
     ! Note that ghost cell values may need to be set if the aux arrays
     ! are used by the Riemann solver(s).
     !
     ! This default version does nothing.
     implicit none
     integer, intent(in) :: mbc,mx,my,maux
     real(kind=8), intent(in) :: xlower,ylower,dx,dy
     real(kind=8), intent(inout) ::  aux(maux,1-mbc:mx+mbc,1-mbc:my+mbc)