2D AMRCLAW: setIndices.f File Reference
setIndices.f File Reference
Functions/Subroutines
subroutine setindices (ist, iend, jst, jend, ilo, ihi, jlo, jhi, ishift, jshift, level)
Function/Subroutine Documentation
setindices()
subroutine setindices (dimension(3) ist, dimension(3) iend, dimension(3) jst, dimension(3) jend, ilo, ihi, jlo, jhi, dimension(3) ishift, dimension(3) jshift, level)
Definition at line 6 of file setIndices.f.
References amr_module::iregsz, amr_module::jregsz, amr_module::xperdom, and amr_module::yperdom.
Referenced by basecheck(), projec2(), and setdomflags().
        use amr_module
        implicit double precision (a-h,o-z)
        dimension ist(3), iend(3), jst(3), jend(3), ishift(3), jshift(3)
 c ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 c  setindices:  for periodicity a region that sticks out is wrapped into
 c               another region.
 c
 c  this is just annoying code this is needed in several places so it became a routine
 c
 c :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        ist(1) = ilo
        ist(2) = 0
        ist(3) = iregsz(level)
        iend(1) = -1
        iend(2) = iregsz(level)-1
        iend(3) = ihi
        jst(1) = jlo
        jst(2) = 0
        jst(3) = jregsz(level)
        jend(1) = -1
        jend(2) = jregsz(level)-1
        jend(3) = jhi
        if (xperdom) then ! regions that stick out of domain get periodically wrapped indices
           ishift(1) = iregsz(level)
           ishift(2) = 0
           ishift(3) = -iregsz(level)
        else   ! no shifting of indices
           ishift(1) = 0
           ishift(2) = 0
           ishift(3) = 0
        endif
        if (yperdom) then
           jshift(1) = jregsz(level)
           jshift(2) = 0
           jshift(3) = -jregsz(level)
        else  ! no shifting of indices
           jshift(1) = 0
           jshift(2) = 0
           jshift(3) = 0
        endif
        return