2D AMRCLAW: stst1.f File Reference
stst1.f File Reference
Functions/Subroutines
subroutine stst1
subroutine inittimers ()
Function/Subroutine Documentation
inittimers()
subroutine inittimers ()
Definition at line 94 of file stst1.f.
References amr_module::timebound, amr_module::timeboundcpu, amr_module::timebufnst, amr_module::timeflagger, amr_module::timeflglvl, amr_module::timegrdfit2, amr_module::timegrdfitall, amr_module::timeregridding, amr_module::timeregriddingcpu, amr_module::timestepgrid, amr_module::timestepgridcpu, amr_module::timetick, amr_module::timetickcpu, amr_module::timeupdating, amr_module::timevalout, and amr_module::timevaloutcpu.
Referenced by stst1().
       use amr_module
       !implicit double precision (a-h,o-z)
       timeflagger        = 0
       timebufnst         = 0
       timestepgrid       = 0
       timestepgridcpu    = 0.d0
       timebound          = 0
       timeboundcpu       = 0.d0
       timegrdfitall      = 0
       timeflagger        = 0
       timeflglvl         = 0
       timeflglvltot      = 0
       timegrdfit2        = 0
       timeregridding     = 0
       timeregriddingcpu  = 0.d0
       timetick           = 0
       timetickcpu        = 0.d0
       timeupdating       = 0
       timevalout         = 0
       timevaloutcpu      = 0.d0
       return
stst1()
subroutine stst1 ()
Definition at line 5 of file stst1.f.
References amr_module::avenumgrids, amr_module::hxposs, amr_module::hyposs, amr_module::icheck, init_alloc(), initbndrylist(), inittimers(), amr_module::intratx, amr_module::intraty, amr_module::iregridcount, amr_module::lenf, amr_module::lfdim, amr_module::lfine, amr_module::lfree, amr_module::lstart, amr_module::maxgr, amr_module::maxlv, amr_module::memsize, amr_module::mxnest, amr_module::ndfree, amr_module::nextfree, amr_module::node, amr_module::null, amr_module::numcells, amr_module::numgrids, and amr_module::tvoll.
Referenced by amr2().
 c
       use amr_module
       implicit double precision (a-h,o-z)
 c
 c :::::::::::::::::::::::::::::: STST1 ::::::::::::::::::::::::::::::::
 c    intialize a few variables needed before calling user set up
 c    routine domain.
 c    the spatial and temporal stepsizes are set. the node array
 c    is kept as a linked list of free nodes.  "ndfree" points to the
 c    head of the list, i.e. first free node.  use first row of each
 c    col to hold this pointer, set by the macro "nextfree".
 c    the free space list, managed in lfree, will have first and
 c    last positions filled with an allocation of zero words,
 c    to avoid boundary cases.
 c ::::::::::::::::::::::::::::::::::::::;::::::::::::::::::::::::::::::
 c
       ndfree = 1
       do 10 i   = 1, maxgr
          node(nextfree,i) = i+1
  10   continue
 c
 c the last free node will have a null pointer
       node(nextfree, maxgr) = null
 c
 c     Initialize dynamic memory
       call init_alloc()
       lfine = 1
 C       do 20 i  = 1, memsize
 C         alloc(i) = WEIRD
 C  20   continue
 c
 c  initialize linked list of alloc storage as well.
 c  first and last locations are dummy placeholders of zero words
 c  of allocation each, to avoid boundary cases.
 c
       do  40 i  = 1, lfdim
         lfree(i,1) = 0
         lfree(i,2) = 0
  40   continue
       lfree(3,1) =memsize + 2
       lfree(2,1) = 1
       lfree(2,2) =memsize
       lenf       = 3
 c  need to manage the boundary List too
 c     do i = 1, bndListSize
 c        bndList(i,nextfree) = i+1
 c     end do
 c     bndList(bndListSize,nextfree) = null
 c     ndfree_bnd = 1
       call initbndrylist()
 c
 c after kcheck integrations of parent grid, move its refinements.
 c finest level grid never needs to have its finer subgrids moved.
 c
       call inittimers()   ! used to be done here, but needs to be called from restarting too when stst1 not called
       do 60 i   = 1, maxlv
          tvoll(i) = 0.d0
          iregridcount(i) = 0
          avenumgrids(i) = 0
          numgrids(i) = 0
          numcells(i) = 0
          lstart(i) = 0
  60      icheck(i) = 0
 c
 c finish initializing spatial and counting arrays
 c
       level      = 2
  70   if (level .gt. mxnest) go to 80
           hxposs(level) = hxposs(level-1) / dble(intratx(level-1))
           hyposs(level) = hyposs(level-1) / dble(intraty(level-1))
           level         = level + 1
       go to 70
  80   continue
       return